name: testing-github-actions_develop
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select the environment
      boolean:
        description: True or False
      choice:
        description: Make a choice

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment variables
      run: echo "TESTING_GLOBAL_REPO_VAR=${{ env.TESTING_GLOBAL_REPO_VAR }}" >> $GITHUB_ENV

    - name: Run the workflow
      run: |
        echo "Testing global repo var: ${{ env.TESTING_GLOBAL_REPO_VAR }}"
        echo "Selected environment: ${{ github.event.inputs.environment }}"
        echo "Boolean value: ${{ github.event.inputs.boolean }}"
        echo "Choice: ${{ github.event.inputs.choice }}"
