name: testing-github-actions_develop
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:


jobs:
  file_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on develop
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "\n$(date)" >> README.md
          ls -a
          cat README.md
          git config user.name amd34
          git config user.email ahmed.naamane92@gmail.com
          git add README.md
          git commit -m "$(date +%s)"
          git tag "$(date +%s)"
          echo "::debug::Set the Octocat variable"
          echo "::debug::Set testing"

      - name: Push tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: git push origin "$(date +%s)"
