name: testing-github-actions_develop
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image to Deploy:'
        required: true
#        default: 'default value'
      promote_after_deploy:
        description: 'Promote after deploy?'
        type: boolean
        required: true
        default: true

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Annotations 1
        env:
          TESTING: ${{ github.event.inputs.image_tag }}
        run: |
          echo "::warning::${TESTING} warnings"
  test2:
    runs-on: ubuntu-latest
    needs: test1
    if: ${{ github.event.inputs.promote_after_deploy }}
    steps:
      - name: Print Annotations 2
        env:
          TESTING: ${{ github.event.image_tag }} 
        run: |
          echo "::notice::${TESTING} Informational message"
  test3:
    runs-on: ubuntu-latest
    needs: test2
    if: ${{ github.event.inputs.promote_after_deploy }}
    steps:
      - name: Print Annotations 2
        env:
          TESTING: ${{ github.event.image_tag }} 
        run: |
          echo "::error::${TESTING} Informational message"

