name: testing-github-actions_develop
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  workflow_dispatch:
    inputs:
      TESTING:
        description: 'Testing input'
        required: true
        default: 'default value'

jobs:
  file_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on develop
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "\n$(date)" >> README.md
          ls -a
          cat README.md
          git config user.name amd34
          git config user.email ahmed.naamane92@gmail.com
          git add README.md
          git commit -m "$(date +%s)"
          git tag "$(date +%s)"
          echo "::debug::Set the Octocat variable"
          echo "::debug::Set testing"

      - name: Print Annotations
        env:
          TESTING: ${{ github.event.inputs.TESTING }}
        run: |
          echo "::debug::Debug message"
          echo "::debug::${TESTING} debug"
          echo "::warning::${TESTING} warnings"
          echo "::error::${TESTING} Error"
          echo "::notice::Informational message"
          echo "##[notice] **Informational message with bold style**"
          echo "::group::Group Name"
          echo "Content within the group"
          echo "::endgroup::"
          #echo "::command::echo 'This command was executed'"
          #echo "::set-env name=MY_VARIABLE::my_value"
          echo "::notice::Informational message with warning: **${TESTING} warnings**"


#      - name: Push tag
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
#        run: git push origin "$(date +%s)"
