name: testing-github-actions_main
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        options:
        - ${{ env.TESTING_GLOBAL_REPO_VAR }}
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - bar
        - baz
jobs:
  check-bats-version___:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: echo "main branch workflow"
      - run: cat README.md
      - run: bats -v
      - run: ls -a
      - run: pwd

